Progress method for Task-Store API
hoodiehq/hoodie-task-server pull request #39
Opened 2017-01-03 17:50 UTC by mbad0la

**WIP** : In reference to #38

2017-01-03 18:24 UTC, inator requested changes
Thanks @mbad0la!looks like you need to add an taskStore.update() and the end of the progress() routine

2017-01-05 16:25 UTC, inator reviewed
@mbad0la - Looks good, but one question...

It would appear that the only enforced structure of the progress update is `name` and `at`, right?  All other included arbitrary properties will be merged and thus passed to the client if I interpret this correctly?  If so, I kinda like that approach, as it maximizes flexibility.  @gr2m - any thoughts on this?

2017-01-05 16:30 UTC, mbad0la commented
Yes @inator, all the arbitrary properties will be merged and overwrite any default properties.

2017-01-05 16:44 UTC, inator commented
Ok - I see an opportunity to break out this progress routine into its own function to also address #40.  That can be done now or later... whatever you decide.  I'll give Gregor an opportunity to comment, then merge if it looks good to him as well.  Thanks for all the effort on this!

2017-01-05 17:38 UTC, mbad0la commented
I'd be more at ease with addressing #40 later. I guess it will be better to track the changes in seperate PRs anyway.

2017-01-05 22:05 UTC, gr2m requested changes

2017-01-05 22:05 UTC, gr2m commented on api/index.js
> +        let progressState = Object.assign({
sorry but we still use es5 at this point, so please use `var` :)

2017-01-05 22:05 UTC, gr2m commented on api/index.js
> +        taskStore.update(taskDoc)
let’s return the promise of `taskStore.update(taskDoc)` here

2017-01-06 03:48 UTC, mbad0la commented on api/index.js
> +        taskStore.update(taskDoc)
Do you mean I have to wrap `taskStore.update(taskDoc)` in a Promise and return it?

2017-01-06 03:49 UTC, mbad0la commented on api/index.js
> +        let progressState = Object.assign({
`Object.assign` is also a spec of ES2015 so that would have to go as well right?

2017-01-06 03:55 UTC, gr2m commented on api/index.js
> +        let progressState = Object.assign({
yes, I missed that. We can use lodash methods, as we use them at other places in Hoodie already

2017-01-06 03:56 UTC, gr2m commented on api/index.js
> +        taskStore.update(taskDoc)
this will do: `return taskStore.update(taskDoc)`. `taskStore.update()` already returns a promise, and it resolves with the task document

2017-01-06 04:02 UTC, mbad0la commented on api/index.js
> +        taskStore.update(taskDoc)
Oh alright! Thanks

2017-01-07 03:58 UTC, gr2m commented on api/index.js
> +        }, options)
I guess `_.assign` will work, too, but maybe [`_.defaults()`](https://lodash.com/docs/4.17.2#defaults) is a better fit for what we want, as it better expresses our intent?

2017-01-07 03:59 UTC, gr2m approved these changes

2017-01-07 04:15 UTC, gr2m commented on api/index.js
> +        }, options)
nevermind, `_defaults` works the wrong way around oops ignore me :D

2017-01-07 04:49 UTC, merged

2017-01-07 04:49 UTC, inator commented
Thanks!